language: python
dist: xenial
sudo: true
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install user-agents
    - pip install tox tox-travis
script: tox
jobs:
  include:
    - stage: lint
      python: "3.6"
      script: tox -e flake8
    - stage: coverage
      python: "3.6"
      script: tox -e coverage
